function Preface() {
  return (
    <>
      <h1 className="text-center">Preface by Aerik Francis</h1>
      <p>
        ELECTRIC NOBODY is an anomaly, an anagram, an amalgam of BODYELECTRONIC. To me, it is a logical conclusion of the text, an expansion of the ethos of the project, a furthering of the collaboration of physical and digital, as well as a continuation of pushing the limits of [its] poetics. 
      </p>
      <p>
        The poems of BODYELECTRONIC constantly surprise me in how they continue to reach beyond the page and into pixel and performance. The poem _Stasis:Lagging_ for example has seen many iterations and continues to multiply every time I share it. The poems inhabit a new sensation on the page, on the stage, in audio, paired with music, paired with visuals, and beyond. And particular poems are unabashed in their fused relationship with the virtual and the artificial, some speaking candidly about awareness and others demonstrating their own poetic intelligence. _Ars Poetica (DoomScroll)_ is a poem with an expansiveness in how it may be read and arranged, given that each tweet that it is composed of are released simultaneously with no real indication of order. So when I say that this current project, ELECTRIC NOBODY is an expansion of the ethos, I think of poems like _Ars Poetica (DoomScroll)_  and _Game Theory: Poetica Ex Machina_ in how they lean into that exponential potentiality that is offered through innovations in technology. 
      </p>
      <p>
        I was most immediately inspired to try this project by thinking about the artist Arca and her release of 100 unique remixes of her song Riquiqui generated by AI. That she considers these the first official remixes to her songs is also significant, especially reflecting on the futuristic sounds her music incorporates. She refers to the accompanying artwork “as an instant gateway to a forever-mutating instance of the song.” I loved that idea of a forever-mutating instance and wanted to imagine what BODYELECTRONIC would look like in collaboration with a digital intelligent sentience, how the central thesis of the project could, too, be a forever -mutating instance. ELECTRIC NOBODY is the first official remix of BODYELECTRONIC.
      </p>
      <p>
        For me, also, this project allowed an opportunity for unique collaboration. In many ways I’ve always wanted to collaborate with Hào as one of my oldest and best friends. We have a lot of shared interests but with unique takes. For example, we are both musicians and music enthusiasts but have very specific and different tastes and abilities. Hào has a lower range and a beautiful texture to their voice, and they play guitar! We have jammed together before, we’ve collaborated before, and so this is another occasion of coming together for a project. Here, though, we make use of both of our current niches– programming and poetry. 
      </p>
      <p>
        Hào can offer more citations and explain more of the technical details about the process of generating the poems of ELECTRIC NOBODY. What I can say simply is that BODYELECTRONIC was the essential sample for the program to derive its content from. We ran the program until we got to 100 poems. These poems then went through a moderation review. While I mostly wanted to keep the poems intact, the program would often generate new titles without original content, as well as original content with reused titles. Moderation included replacing titles with originally generated titles as well as removing inappropriate and explicit content.
      </p>
      <p>
        <strong>It is important to note a content warning</strong>: some of these poems generated included explicit sexual or violent content, so discretion is recommended when reading through. We do know that many AI technologies have a problem of replicating the biases and violences of the humans who program them. In that spirit, I did want to leave the poems untouched as much as possible to continue thinking about that relationship. Given that problem, however, moderation is necessary. 
      </p>
      <p>
        The poem sets are randomized on the site with one appearing visible and a generated captcha to get through to the next poem. This is very much inspired by the project The Woman Factory by Ava Hoffman in which her poems were also separated by captchas uniquely/specifically generated for the project. While we only created a fixed set of poems, one can imagine creating an infinite amount, and to me the imagination is the most important part, that exponential potentiality.
      </p>
      <p>
        The poems surprised and delighted me, emphasizing that they are indeed poems and that they do have things to teach us just the same about form, structure, language, syntax, order, sound, feeling. In a way, it felt like a satirizing or a dangerous exaggeration of the work and words of BODYELECTRONIC. But mostly, I am amazed at how these poems extend and stretch the conversations in BODYELECTRONIC in myriad vectors. Some of these poems are shocking and stunning. Some of these poems are hilarious nonsense. Some of these poems are queer and some are just questioning. Some of these poems heavily rely on phrases and repetitions from BODYELECTRONIC. Some of these poems veer completely in their own direction with their own concerns, their own obsessions, their own syntax and form, and even their own language (sometimes they create their own words and characters). For example I am really fascinated with the set of “Naughty Jackie” poems that were created. I love how striking the titles generated are. 
      </p>
      <p>
        My biggest hope for those who interact with this project is to simply be inspired. Maybe you are inspired by an idea, a word, or a phrase. Maybe you are inspired into thinking more about coding, programming, and computer science. Maybe you are inspired to look specifically in to AI poetry, coding poetry, and the intersections of programming languages and literary languages. Maybe you are inspired to collaborate with a friend (we actually had a fun time putting this project together!). Maybe you are inspired to read more, to read more of the artists and projects that inspired this project, or to check out BODYELECTRONIC. Maybe you are inspired to write or make music or make art of some sort. Maybe you are just inspired to think deeply. Maybe you are inspired to keep reading poems of ELECTRIC NOBODY. Etc Etc Etc. I just hope that some kind of inspiration can be generated and some kind of artistic permission be granted.
      </p>
      <p>
        This is ELECTRIC NOBODY.
      </p>
      <p>
        Always with warmth,
      </p>
      <p>
        Aerik
      </p>
    </>
  )
}

export default Preface;